# Generated by Django 5.1.1 on 2024-09-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter_count',
            field=models.IntegerField(default=0),
        ),
    ]
