# Generated by Django 5.1.1 on 2024-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vote_voter_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
